builds:
  - main: main.go
    binary: macdef
    goos:
      - darwin
    goarch:
      - amd64
archive:
  format: zip
  replacements:
    darwin: macOS
brew:
  github:
    owner: grapswiz
    name: homebrew-macdef
  caveats: "May the macdef be with you"
  homepage: "https://github.com/grapswiz/macdef"
  description: "change and save defaults settings for Mac."