defaults: &defaults
  working_directory: /go/src/github.com/grapswiz/macdef
  docker:
    - image: circleci/golang:1.9

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - deploy:
          name: goreleaser
          command: |
            curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              ignore: /.*/