[[items]]
name = "showhidden"
description = "Show hidden apps"
type = "bool"
commands = [
"defaults write com.apple.Dock showhidden -bool {{.Value}}"
]

[[items]]
name = "static-only"
description = "Only show applications that are running"
type = "bool"
commands = [
"defaults write com.apple.Dock static-only -bool {{.Value}}"
]

[[items]]
name = "autohide"
description = "Hide Dock"
type = "bool"
commands = [
"defaults write com.apple.Dock autohide -bool {{.Value}}"
]

[[items]]
name = "orientation"
description = "Dock position"
type = "string literal"
values = [
"bottom",
"left"
]
commands = [
"defaults write com.apple.dock orientation {{.Value}}"
]